#!/usr/bin/env python3
"""
Test parsing utilities for various test frameworks.

This module provides parsers for extracting test results from different
test framework outputs including:
- JUnit XML (pytest, unittest, Java)
- Go JSON output
- Jest/Vitest JSON output
- Mocha JSON output
- GTest JSON output
- Cargo-nextest output
- Bun text output
- And many more...
"""

from __future__ import annotations

import json
import logging
import re
import xml.etree.ElementTree as ET
logger = logging.getLogger(__name__)


def parse_compact_format(output: str) -> dict[str, str] | None:
    """Parse compact PARSED_TESTS format from sandbox pre-processing.
    
    This format is generated by the in-container parser (shared/parse_test_output.py)
    when it successfully parses test output inside Docker.
    
    Supports two formats:
    
    Format 1 (legacy - pipe-separated):
        PARSED_TESTS
        PASSED:test1|test2|test3
        FAILED:test4|test5
        SKIPPED:test6|test7
    
    Format 2 (new - one test per line, supports many tests):
        PARSED_TESTS
        COUNTS:10,2,3
        P|test_name_1
        P|test_name_2
        F|test_name_3
        S|test_name_4
    
    Returns:
        Dict mapping test names to status, or None if not in this format.
    """
    if "PARSED_TESTS" not in output:
        return None
    
    results = {}
    lines = output.strip().split("\n")
    
    for line in lines:
        # New format: P|test_name, F|test_name, S|test_name
        if line.startswith("P|"):
            test_name = line[2:].strip()
            if test_name:
                results[test_name] = "PASSED"
        elif line.startswith("F|"):
            test_name = line[2:].strip()
            if test_name:
                results[test_name] = "FAILED"
        elif line.startswith("S|"):
            test_name = line[2:].strip()
            if test_name:
                results[test_name] = "SKIPPED"
        # Legacy format: PASSED:test1|test2|test3
        elif line.startswith("PASSED:"):
            test_names = line[7:].split("|")
            for name in test_names:
                if name.strip():
                    results[name.strip()] = "PASSED"
        elif line.startswith("FAILED:"):
            test_names = line[7:].split("|")
            for name in test_names:
                if name.strip():
                    results[name.strip()] = "FAILED"
        elif line.startswith("SKIPPED:"):
            test_names = line[8:].split("|")
            for name in test_names:
                if name.strip():
                    results[name.strip()] = "SKIPPED"
    
    return results if results else None


def _parse_embedded_test_results(
    text_output: str, test_prefix: str = ""
) -> dict[str, str]:
    """Parse embedded test results from system-out text.

    This handles cases like wolfssl where a single ctest testcase runs many individual tests
    and outputs them in a specific format within <system-out>.

    Args:
        text_output: The text content from <system-out>
        test_prefix: Prefix to add to test names (usually the testcase name)

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
    """
    results = {}

    # Pattern 1: Numbered test format (wolfssl API tests)
    numbered_pattern = re.compile(
        r"^\s*\d+:\s+([^\s:]+(?:\s+[^\s:]+)*?)\s*:\s*(passed|failed|skipped)",
        re.MULTILINE | re.IGNORECASE,
    )

    for match in numbered_pattern.finditer(text_output):
        test_name = match.group(1).strip()
        status = match.group(2).lower()

        if test_prefix:
            test_id = f"{test_prefix}::{test_name}"
        else:
            test_id = test_name

        if status == "passed":
            results[test_id] = "PASSED"
        elif status == "failed":
            results[test_id] = "FAILED"
        elif status == "skipped":
            results[test_id] = "SKIPPED"

    # Pattern 2: Unit test format (wolfssl unit tests)
    unit_pattern = re.compile(
        r"^([A-Za-z0-9_\-/]+(?:[ \t]+[A-Za-z0-9_\-/]+){0,5}?)[ \t]+test[ \t]+(passed|failed)!",
        re.MULTILINE | re.IGNORECASE,
    )

    for match in unit_pattern.finditer(text_output):
        test_name = match.group(1).strip()
        status = match.group(2).lower()

        if "---" in test_name or len(test_name) > 50:
            continue

        if test_prefix:
            test_id = f"{test_prefix}::{test_name}"
        else:
            test_id = test_name

        if status == "passed":
            results[test_id] = "PASSED"
        elif status == "failed":
            results[test_id] = "FAILED"

    # Pattern 3: FAILURES section (wolfssl API tests)
    failures_section = re.search(
        r"FAILURES:\s*\n(.*?)(?:\n\s*End|$)", text_output, re.DOTALL
    )
    if failures_section:
        failure_pattern = re.compile(
            r"^\s*\d+:\s+([^\s:]+(?:\s+[^\s:]+)*)", re.MULTILINE
        )
        for match in failure_pattern.finditer(failures_section.group(1)):
            test_name = match.group(1).strip()
            if test_prefix:
                test_id = f"{test_prefix}::{test_name}"
            else:
                test_id = test_name
            results[test_id] = "FAILED"

    return results


def parse_junit_xml(xml_content: str) -> dict[str, str] | None:
    """Parse JUnit XML to extract test results.

    IMPORTANT: We prioritize finding valid test results over detecting errors.
    Even if output contains errors (import errors, syntax errors, etc.), if we find valid
    XML test results, we parse and return them. We only return None if we're certain
    the framework didn't run (no test results + error indicators).

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If test framework failed to run (not the same as tests failing)
    """
    results = {}
    found_any_xml = False

    # Handle multiple concatenated XML documents
    xml_docs = xml_content.split("<?xml")

    for i, doc in enumerate(xml_docs):
        if i == 0 and not doc.strip():
            continue

        if i > 0:
            doc = "<?xml" + doc

        if not doc.strip():
            continue

        try:
            tree = ET.fromstring(doc.strip())
            found_any_xml = True
        except ET.ParseError:
            xml_start = doc.find("<testsuite")
            if xml_start == -1:
                xml_start = doc.find("<testsuites")
            if xml_start == -1:
                continue

            xml_end = doc.find("</testsuites>", xml_start)
            if xml_end > xml_start:
                xml_extracted = doc[xml_start : xml_end + len("</testsuites>")]
            else:
                xml_end = doc.find("</testsuite>", xml_start)
                if xml_end > xml_start:
                    xml_extracted = doc[xml_start : xml_end + len("</testsuite>")]
                else:
                    continue

            try:
                tree = ET.fromstring(xml_extracted)
                found_any_xml = True
            except ET.ParseError:
                continue

        for testcase in tree.iter("testcase"):
            classname = testcase.get("classname", "")
            name = testcase.get("name", "")
            test_id = f"{classname}::{name}" if classname else name

            system_out = testcase.find("system-out")
            embedded_results = {}
            if system_out is not None and system_out.text:
                embedded_results = _parse_embedded_test_results(
                    system_out.text, classname or name
                )

            if embedded_results:
                results.update(embedded_results)
            elif (
                testcase.find("failure") is not None
                or testcase.find("error") is not None
            ):
                results[test_id] = "FAILED"
            elif testcase.find("skipped") is not None:
                results[test_id] = "SKIPPED"
            else:
                results[test_id] = "PASSED"

    if not found_any_xml and not results:
        error_indicators = [
            "ERROR: ",
            "ImportError:",
            "ModuleNotFoundError:",
            "SyntaxError:",
            "FAILED ",
            "INTERNALERROR",
            "collection errors",
            "error: ",
            "fatal error:",
            "cannot find symbol",
            "error: build had",
            "error: terminated",
        ]
        has_errors = any(indicator in xml_content for indicator in error_indicators)
        return None if has_errors else results

    return results


def parse_go_json(json_output: str) -> dict[str, str] | None:
    """Parse Go test -json output (newline-delimited JSON).

    Prioritizes finding valid test results over detecting errors. Even if output
    contains errors (module errors, build errors, etc.), if we find valid test
    results JSON, we parse and return it.

    Args:
        json_output: Raw output from `go test -json` command.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED).
        None: If Go tests failed to run (not the same as tests failing).
    """
    results: dict[str, str] = {}
    has_valid_output = False

    for line in json_output.strip().split("\n"):
        line = line.strip()
        if not line:
            continue

        try:
            event = json.loads(line)
            has_valid_output = True
            action = event.get("Action")

            # Handle test-level events
            if "Test" in event and action in ("pass", "fail", "skip"):
                test_name = event.get("Test", "")
                if test_name:
                    package = event.get("Package", "")
                    test_id = f"{package}::{test_name}" if package else test_name
                    if action == "pass":
                        results[test_id] = "PASSED"
                    elif action == "fail":
                        results[test_id] = "FAILED"
                    elif action == "skip":
                        results[test_id] = "SKIPPED"

            # Handle package-level failures (no Test field)
            elif "Package" in event and "Test" not in event and action == "fail":
                package = event.get("Package", "")
                results[f"{package}::package"] = "FAILED"

        except json.JSONDecodeError:
            # Handle plaintext Go test output (non-JSON)
            # Formats: "ok package 0.123s", "FAIL package 0.123s", "FAIL package [build failed]"

            if match := re.match(r"^FAIL\s+(\S+)\s+\[build failed\]", line):
                results[match.group(1)] = "FAILED"
                has_valid_output = True
            elif match := re.match(r"^ok\s+(\S+)\s+[\d.]+s", line):
                results[match.group(1)] = "PASSED"
                has_valid_output = True
            elif match := re.match(r"^FAIL\s+(\S+)\s+[\d.]+s", line):
                results[match.group(1)] = "FAILED"
                has_valid_output = True

    # Check for error indicators only if no valid output found
    if not has_valid_output and not results:
        error_indicators = (
            "go: cannot find main module",
            "can't load package",
            "pattern matches no packages",
            "build constraints exclude all Go files",
            "no required module provides package",
        )
        if any(indicator in json_output for indicator in error_indicators):
            return None

    return results


def parse_jest_vitest_json(json_output: str) -> dict[str, str] | None:
    """Parse Jest/Vitest JSON output.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If Jest itself failed to run (not the same as tests failing)
    """
    results = {}
    data = None

    # Try direct JSON parsing first
    try:
        data = json.loads(json_output.strip())
    except json.JSONDecodeError:
        # Try to find JSON object start with various patterns
        patterns = ['{"numFailed', '{"numTotalTest', '{"test', '{\n  "num', '{\n"num']
        json_start = -1
        for pattern in patterns:
            json_start = json_output.find(pattern)
            if json_start != -1:
                break
        
        # Also try to find any '{' that starts a JSON object
        if json_start == -1:
            for i, char in enumerate(json_output):
                if char == '{':
                    json_start = i
                    break
        
        if json_start == -1:
            error_indicators = [
                "error TS",
                "ELIFECYCLE",
                "npm ERR!",
                "Error: Cannot find module",
                "SyntaxError:",
                "Test suite failed to run",
                "FAIL ",
            ]
            has_errors = any(indicator in json_output for indicator in error_indicators)
            return None if has_errors else results

        decoder = json.JSONDecoder()
        try:
            data, _ = decoder.raw_decode(json_output[json_start:])
        except json.JSONDecodeError:
            return None
    
    if data is None:
        return results

    if "error" in data and "code" in data.get("error", {}):
        return None

    if "testResults" in data:
        for test_result in data.get("testResults", []):
            file_path = test_result.get("name", "")
            suite_status = test_result.get("status", "")
            assertions = test_result.get("assertionResults", [])

            if suite_status == "failed" and len(assertions) == 0:
                test_id = f"{file_path}::suite"
                results[test_id] = "FAILED"
                continue

            for assertion in assertions:
                full_name = assertion.get("fullName", "")
                title = assertion.get("title", "")
                status = assertion.get("status", "")
                test_id = (
                    f"{file_path}::{full_name}"
                    if full_name
                    else f"{file_path}::{title}"
                )

                if status == "passed":
                    results[test_id] = "PASSED"
                elif status == "failed":
                    results[test_id] = "FAILED"
                elif status in ["pending", "skipped"]:
                    results[test_id] = "SKIPPED"

    if "testResults" not in data:
        return None

    return results


def parse_mocha_json(json_output: str) -> dict[str, str] | None:
    """Parse Mocha JSON output.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If Mocha itself failed to run (not the same as tests failing)
    """
    results = {}

    try:
        data = json.loads(json_output.strip())
        if "stats" not in data:
            data = None
    except json.JSONDecodeError:
        data = None

    if data is None:
        stats_pos = json_output.find('"stats"')
        if stats_pos == -1:
            error_indicators = [
                "Error: Cannot find module",
                "SyntaxError:",
                "TypeError:",
                "ReferenceError:",
                "No test files found",
            ]
            has_errors = any(indicator in json_output for indicator in error_indicators)
            return None if has_errors else results

        json_start = json_output.rfind("{", 0, stats_pos)
        if json_start == -1:
            return None

        json_portion = json_output[json_start:]

        decoder = json.JSONDecoder()
        try:
            data, _ = decoder.raw_decode(json_portion)
        except json.JSONDecodeError:
            return None

        if "stats" not in data:
            return None

    for test in data.get("passes", []):
        file_path = test.get("file", "")
        full_title = test.get("fullTitle", "")
        test_id = f"{file_path}::{full_title}" if full_title else file_path
        results[test_id] = "PASSED"

    for test in data.get("failures", []):
        file_path = test.get("file", "")
        full_title = test.get("fullTitle", "")
        test_id = f"{file_path}::{full_title}" if full_title else file_path
        results[test_id] = "FAILED"

    for test in data.get("pending", []):
        file_path = test.get("file", "")
        full_title = test.get("fullTitle", "")
        test_id = f"{file_path}::{full_title}" if full_title else file_path
        results[test_id] = "SKIPPED"

    return results


def parse_gtest_json(json_output: str) -> dict[str, str] | None:
    """Parse Google Test JSON output.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If GTest itself failed to run (not the same as tests failing)
    """
    results = {}
    data = None

    # Try to parse as clean JSON first
    try:
        data = json.loads(json_output.strip())
        if "testsuites" not in data:
            data = None
    except json.JSONDecodeError:
        pass

    # If that failed, try to find JSON object in the output
    if data is None:
        # Look for various JSON start patterns
        for pattern in ['{"tests"', '{"testsuites"', '{\n  "tests"', '{\n  "testsuites"']:
            json_start = json_output.find(pattern)
            if json_start != -1:
                break
        
        if json_start == -1:
            error_indicators = [
                "error:",
                "undefined reference to",
                "fatal error:",
                "cannot find -l",
                ": No such file or directory",
            ]
            has_errors = any(indicator in json_output for indicator in error_indicators)
            return None if has_errors else results

        json_portion = json_output[json_start:]
        decoder = json.JSONDecoder()
        try:
            data, _ = decoder.raw_decode(json_portion)
        except json.JSONDecodeError:
            return None

        if "testsuites" not in data:
            return None

    testsuites = data.get("testsuites", [])
    if not isinstance(testsuites, list):
        testsuites = [testsuites] if isinstance(testsuites, dict) else []

    for testsuite in testsuites:
        suite_name = testsuite.get("name", "")

        test_cases = testsuite.get("testsuite", [])
        if not test_cases:
            test_cases = testsuite.get("tests", [])

        for test_case in test_cases:
            test_name = test_case.get("name", "")
            classname = test_case.get("classname", suite_name)

            test_id = f"{classname}::{test_name}" if classname else test_name

            status = test_case.get("status", "RUN")
            result = test_case.get("result", "COMPLETED")

            failures = test_case.get("failures", [])
            if failures and len(failures) > 0:
                results[test_id] = "FAILED"
            elif status == "NOTRUN" or result == "SKIPPED":
                results[test_id] = "SKIPPED"
            elif result == "COMPLETED" or status == "RUN":
                results[test_id] = "PASSED"
            else:
                results[test_id] = "FAILED"

    return results


def parse_gtest_console(output: str) -> dict[str, str] | None:
    """Parse Google Test console output.
    
    Parses output format like:
        [ RUN      ] TestIRac.Airton
        [       OK ] TestIRac.Airton (0 ms)
        [  FAILED  ] TestIRac.SomeTest (1 ms)
        [  SKIPPED ] TestIRac.Skip (0 ms)
    
    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If no GTest output found
    """
    results = {}
    
    # Pattern to match GTest console output lines
    # [ RUN      ] SuiteName.TestName
    # [       OK ] SuiteName.TestName (N ms)
    # [  FAILED  ] SuiteName.TestName (N ms)
    # [  SKIPPED ] SuiteName.TestName (N ms)
    
    run_pattern = re.compile(r'\[\s*RUN\s*\]\s+(\S+)')
    ok_pattern = re.compile(r'\[\s*OK\s*\]\s+(\S+)')
    failed_pattern = re.compile(r'\[\s*FAILED\s*\]\s+(\S+)')
    skipped_pattern = re.compile(r'\[\s*SKIPPED\s*\]\s+(\S+)')
    
    # Track which tests we've seen as RUN
    seen_tests = set()
    
    for line in output.split('\n'):
        line = line.strip()
        
        # Match RUN to track started tests
        run_match = run_pattern.search(line)
        if run_match:
            test_name = run_match.group(1)
            # Normalize: GTest uses . but we use :: for consistency
            test_id = test_name.replace('.', '::')
            seen_tests.add(test_id)
            continue
        
        # Match OK (PASSED)
        ok_match = ok_pattern.search(line)
        if ok_match:
            test_name = ok_match.group(1)
            test_id = test_name.replace('.', '::')
            results[test_id] = "PASSED"
            continue
        
        # Match FAILED
        failed_match = failed_pattern.search(line)
        if failed_match:
            test_name = failed_match.group(1)
            test_id = test_name.replace('.', '::')
            results[test_id] = "FAILED"
            continue
        
        # Match SKIPPED
        skipped_match = skipped_pattern.search(line)
        if skipped_match:
            test_name = skipped_match.group(1)
            test_id = test_name.replace('.', '::')
            results[test_id] = "SKIPPED"
            continue
    
    # Any tests that were RUN but not marked as OK/FAILED/SKIPPED are considered FAILED
    for test_id in seen_tests:
        if test_id not in results:
            results[test_id] = "FAILED"
    
    return results if results else None


def parse_maven_text_output(text_output: str) -> dict[str, str]:
    """Parse Maven text output for test results."""
    results = {}

    summary_pattern = (
        r"Tests run: (\d+),\s*Failures: (\d+),\s*Errors: (\d+),\s*Skipped: (\d+)"
    )

    compilation_error_pattern = r"\[ERROR\].*?testCompile.*?Compilation failure"
    if re.search(compilation_error_pattern, text_output, re.DOTALL | re.IGNORECASE):
        test_file_pattern = r"/workspace/repo/[^/]+/src/test/java/([\w/]+)\.java"
        for match in re.finditer(test_file_pattern, text_output):
            test_class = match.group(1).replace("/", ".")
            results[f"{test_class}::compile"] = "FAILED"
        if results:
            return results

    if "BUILD FAILURE" in text_output:
        if not results:
            results["maven::build"] = "FAILED"
        return results

    lines = text_output.split("\n")
    current_module = None

    for line in lines:
        if "Building" in line and "[" in line and "]" in line:
            parts = line.split("Building")
            if len(parts) > 1:
                module_parts = parts[1].strip().split()
                if len(module_parts) > 0:
                    current_module = module_parts[0]

        summary_match = re.search(summary_pattern, line)
        if summary_match:
            total = int(summary_match.group(1))
            failures = int(summary_match.group(2))
            errors = int(summary_match.group(3))
            skipped = int(summary_match.group(4))

            if total > 0:
                module_name = current_module or "unknown"
                passed = total - failures - errors - skipped

                for j in range(passed):
                    results[f"{module_name}::test_{j+1}"] = "PASSED"
                for j in range(failures + errors):
                    results[f"{module_name}::test_failed_{j+1}"] = "FAILED"
                for j in range(skipped):
                    results[f"{module_name}::test_skipped_{j+1}"] = "SKIPPED"
    return results


def parse_cargo_nextest(output: str) -> dict[str, str] | None:
    """Parse cargo-nextest text output.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If cargo-nextest failed to run (not the same as tests failing)
    """
    results = {}

    test_line_pattern = re.compile(
        r"^\s*(PASS|FAIL|SIGKILL|SKIP)\s+\[.*?\]\s+(.+)$", re.MULTILINE
    )

    for match in test_line_pattern.finditer(output):
        status = match.group(1)
        test_name = match.group(2).strip()

        if status == "PASS":
            results[test_name] = "PASSED"
        elif status in ("FAIL", "SIGKILL"):
            results[test_name] = "FAILED"
        elif status == "SKIP":
            results[test_name] = "SKIPPED"

    if not results:
        error_indicators = [
            "error[E",
            "error: could not compile",
            "error: linking with",
            "error: aborting due to",
        ]
        has_errors = any(indicator in output for indicator in error_indicators)
        return None if has_errors else results

    return results


def parse_bun_text(text_output: str) -> dict[str, str] | None:
    """Parse Bun test framework output.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If Bun itself failed to run (not the same as tests failing)
    """
    results = {}
    current_file = None
    current_describe = None

    for line in text_output.split("\n"):
        if re.match(r"^[^\s].*\.(ts|js|tsx|jsx):?\s*$", line.strip()):
            current_file = line.strip().rstrip(":")
            current_describe = None
            continue

        describe_match = re.match(r"^\s+([^✓✗\n]+):\s*$", line)
        if describe_match:
            current_describe = describe_match.group(1).strip()
            continue

        clean_line = re.sub(r"\x1b\[[0-9;]*m", "", line)

        pass_match = re.match(r"^\s*✓\s+(.+?)(?:\s+\[[\d.]+m?s\])?\s*$", clean_line)
        if pass_match:
            test_name = pass_match.group(1).strip()
            test_id = test_name
            if current_file:
                test_id = f"{current_file}::{test_name}"
            if current_describe:
                test_id = f"{current_file}::{current_describe} > {test_name}"
            results[test_id] = "PASSED"
            continue

        fail_match = re.match(r"^\s*✗\s+(.+?)(?:\s+\[[\d.]+m?s\])?\s*$", clean_line)
        if fail_match:
            test_name = fail_match.group(1).strip()
            test_id = test_name
            if current_file:
                test_id = f"{current_file}::{test_name}"
            if current_describe:
                test_id = f"{current_file}::{current_describe} > {test_name}"
            results[test_id] = "FAILED"
            continue

        alt_fail_match = re.match(r"^\s*FAIL\s+(.+?)\s+>\s+(.+?)\s*$", clean_line)
        if alt_fail_match:
            file_path = alt_fail_match.group(1).strip()
            test_path = alt_fail_match.group(2).strip()
            test_id = f"{file_path}::{test_path}"
            results[test_id] = "FAILED"
            continue

    if not results:
        summary_match = re.search(
            r"(\d+)\s+pass(?:ing|ed)?.*?(\d+)\s+fail(?:ing|ed)?", text_output.lower()
        )
        if summary_match:
            passed = int(summary_match.group(1))
            failed = int(summary_match.group(2))

            for i in range(passed):
                results[f"test_{i+1}"] = "PASSED"
            for i in range(failed):
                results[f"test_failed_{i+1}"] = "FAILED"

    if not results:
        error_indicators = [
            "error TS",
            "Error: Cannot find module",
            "SyntaxError:",
            "error: ",
            "Error:",
            "ModuleNotFoundError",
            "bun: command not found",
            "panicked at",
            "Segmentation fault",
        ]
        has_errors = any(indicator in text_output for indicator in error_indicators)
        return None if has_errors else results

    return results


def parse_cppunit_text(text_output: str) -> dict[str, str] | None:
    """Parse CppUnit text output for test results.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If CppUnit failed to run (not the same as tests failing)
    """
    results = {}

    test_line_pattern = re.compile(
        r"^([A-Za-z_][A-Za-z0-9_]*::[A-Za-z_][A-Za-z0-9_]*)\s*:\s*(OK|FAIL|ERROR)$",
        re.MULTILINE,
    )

    for match in test_line_pattern.finditer(text_output):
        test_name = match.group(1).strip()
        status = match.group(2).strip()

        if status == "OK":
            results[test_name] = "PASSED"
        elif status in ["FAIL", "ERROR"]:
            results[test_name] = "FAILED"

    if not results:
        error_indicators = [
            "error:",
            "undefined reference to",
            "fatal error:",
            "ld returned",
            "cannot find -l",
        ]
        has_errors = any(indicator in text_output for indicator in error_indicators)
        return None if has_errors else results

    return results


def parse_minitest_text(
    text_output: str, test_metadata_path: str | None = None
) -> dict[str, str]:
    """Parse mini.nvim (MiniTest) test framework output."""
    results = {}

    fail_pattern = re.compile(
        r"^(?:\x1b\[\d+(?:;\d+)?m)?FAIL(?:\x1b\[0m)?\s+in\s+([^|]+)\s*\|\s*([^|:]+)(?:\s*\|\s*([^:]+))?:",
        re.MULTILINE,
    )

    for match in fail_pattern.finditer(text_output):
        file_path = match.group(1).strip()
        group = match.group(2).strip()
        test_name = match.group(3).strip() if match.group(3) else ""

        if test_name:
            test_id = f"{file_path} | {group} | {test_name}"
        else:
            test_id = f"{file_path} | {group}"

        results[test_id] = "FAILED"

    return results


def parse_telescope_text(text_output: str) -> dict[str, str] | None:
    """Parse telescope test framework output.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If telescope failed to run (not the same as tests failing)
    """
    results = {}

    for line in text_output.split("\n"):
        line = line.strip()

        if "✓" in line:
            test_name = line.split("✓", 1)[1].strip()
            if test_name:
                results[test_name] = "PASSED"
        elif line.lower().startswith("success:"):
            test_name = line.split(":", 1)[1].strip()
            if test_name:
                results[test_name] = "PASSED"

        elif "✗" in line:
            test_name = line.split("✗", 1)[1].strip()
            if test_name:
                results[test_name] = "FAILED"
        elif line.lower().startswith("failed:"):
            test_name = line.split(":", 1)[1].strip()
            if test_name:
                results[test_name] = "FAILED"

        elif line.startswith("- ") and "skip" in line.lower():
            test_name = line[2:].strip()
            test_name = re.sub(
                r"\s*\(skipped\)\s*$", "", test_name, flags=re.IGNORECASE
            )
            if test_name:
                results[test_name] = "SKIPPED"
        elif line.lower().startswith("skipped:"):
            test_name = line.split(":", 1)[1].strip()
            if test_name:
                results[test_name] = "SKIPPED"

    if not results:
        summary_pattern = r"(\d+)\s+passed.*?(\d+)\s+failed"
        match = re.search(summary_pattern, text_output.lower())
        if match:
            passed = int(match.group(1))
            failed = int(match.group(2))

            for i in range(passed):
                results[f"test_{i+1}"] = "PASSED"
            for i in range(failed):
                results[f"test_failed_{i+1}"] = "FAILED"

    if not results:
        error_indicators = [
            "Error:",
            "error loading module",
            "attempt to call",
            "bad argument",
            "stack traceback:",
        ]
        has_errors = any(indicator in text_output for indicator in error_indicators)
        return None if has_errors else results

    return results


def parse_lust_text(text_output: str) -> dict[str, str]:
    """Parse lust test framework output."""
    results = {}

    test_pattern = re.compile(r"^\s*(.+?)\s+\.\.\.\s+(ok|FAILED|ERROR)", re.MULTILINE)
    matches = test_pattern.findall(text_output)

    if matches:
        for test_name, status in matches:
            test_name = test_name.strip()
            if status == "ok":
                results[test_name] = "PASSED"
            else:
                results[test_name] = "FAILED"
        return results

    failure_pattern = re.compile(r"^([^\s:]+\.lua):(\d+):\s*(.+)$", re.MULTILINE)
    failures = failure_pattern.findall(text_output)

    if failures:
        for filepath, _, description in failures:
            test_id = f"{filepath}::{description.strip()}"
            results[test_id] = "FAILED"

    summary_match = re.search(
        r"(\d+)\s+tests?,\s+(\d+)\s+failures?", text_output.lower()
    )
    if summary_match:
        total_tests = int(summary_match.group(1))
        failures = int(summary_match.group(2))

        if not results:
            passed = total_tests - failures
            for i in range(passed):
                results[f"test_{i+1}"] = "PASSED"
            for i in range(failures):
                results[f"test_failed_{i+1}"] = "FAILED"
            return results

    if not results:
        if "0 failures" in text_output.lower() or "0 errors" in text_output.lower():
            results["test_suite"] = "PASSED"
        else:
            results["test_suite"] = "FAILED"

    return results


def parse_bespoke_output(output: str, validation_code: str | None = None) -> dict[str, str] | None:
    """Parse bespoke/custom test output using validation_code_snippet.
    
    Bespoke tests have a custom validation snippet that evaluates the output.
    If no validation code is provided, falls back to generic success/failure detection.
    
    Args:
        output: Raw test output
        validation_code: Python code snippet that sets result dict (optional)
    
    Returns:
        dict mapping test_id to status, or None if framework failed to run
    """
    results = {}
    
    if validation_code:
        # Execute the validation code snippet
        # The snippet should set result = {"test_name": "PASSED"/"FAILED"}
        try:
            local_vars: dict = {"output": output, "result": {}}
            exec(validation_code, {}, local_vars)
            raw_result = local_vars.get("result", {})
            
            # Normalize the results
            for test_id, status in raw_result.items():
                if isinstance(status, str):
                    status_upper = status.upper()
                    if status_upper in ("PASSED", "PASS", "OK", "SUCCESS"):
                        results[test_id] = "PASSED"
                    elif status_upper in ("FAILED", "FAIL", "ERROR", "FAILURE"):
                        results[test_id] = "FAILED"
                    elif status_upper in ("SKIPPED", "SKIP", "PENDING"):
                        results[test_id] = "SKIPPED"
            
            if results:
                return results
        except Exception:
            pass
    
    # Fallback: generic success/failure detection
    return parse_bespoke_libgeos(output)


def parse_bespoke_libgeos(text_output: str) -> dict[str, str] | None:
    """Parse libgeos/GEOS test output format.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If libgeos tests failed to run (not the same as tests failing)
    """
    results = {}

    # Parse individual test group lines: "TestSuite::TestName: ...."
    test_line_pattern = re.compile(
        r"^([a-zA-Z_][a-zA-Z0-9_:]*::[a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*(.+?)(?:\n|$)",
        re.MULTILINE,
    )

    for match in test_line_pattern.finditer(text_output):
        test_id = match.group(1)
        test_output_line = match.group(2)
        has_failure = bool(
            re.search(r"\[.*=[FX]\]|(?<!\w)[FX](?!\w)", test_output_line)
        )
        results[test_id] = "FAILED" if has_failure else "PASSED"

    if results:
        # If the suite completed successfully, keep individual results as-is.
        # If the suite timed out or crashed (no summary), the run is incomplete —
        # mark everything FAILED so new tests added by the golden patch show as F2P.
        if "tests summary: ok:" not in text_output:
            results = {k: "FAILED" for k in results}
        return results

    # No individual test lines found — fall back to synthetic "yes" marker
    if "tests summary: ok:" in text_output:
        return {"yes": "PASSED"}
    if "tests summary:" in text_output and "ok:" not in text_output:
        return {"yes": "FAILED"}

    error_indicators = [
        "error:",
        "undefined reference",
        "fatal error:",
        "ld returned",
        "cannot find -l",
    ]
    has_errors = any(indicator in text_output for indicator in error_indicators)
    return None if has_errors else results


def _normalize_swift_test_name(raw_name: str) -> str:
    """Normalize XCTest case identifiers from swift test console output."""
    name = raw_name.strip()

    if name.startswith("-[") and name.endswith("]"):
        inner = name[2:-1].strip()
        if " " in inner:
            class_name, method = inner.split(" ", 1)
            return f"{class_name}::{method}"
        return inner

    if "." in name:
        parts = name.split(".", 1)
        return f"{parts[0]}::{parts[1]}"

    return name


def parse_swift_test_text(text_output: str) -> dict[str, str]:
    """Parse vanilla `swift test` console output (without --xunit-output)."""
    results = {}
    test_case_pattern = re.compile(
        r"Test Case '([^']+)' (passed|failed|skipped)", re.IGNORECASE
    )

    for match in test_case_pattern.finditer(text_output):
        raw_name, status = match.groups()
        test_id = _normalize_swift_test_name(raw_name)
        results[test_id] = status.upper()

    if results:
        return results

    summary_match = re.search(
        r"Executed\s+(\d+)\s+tests?,\s+with\s+(\d+)\s+failures?",
        text_output,
        re.IGNORECASE,
    )
    if summary_match:
        total_tests = int(summary_match.group(1))
        failures = int(summary_match.group(2))
        passes = max(total_tests - failures, 0)

        for i in range(passes):
            results[f"swift_test_pass_{i+1}"] = "PASSED"
        for i in range(failures):
            results[f"swift_test_fail_{i+1}"] = "FAILED"

    return results


def parse_xctest_output(output: str) -> dict[str, str]:
    """Parse XCTest results, preferring XML when available."""
    xml_results = parse_junit_xml(output)
    if xml_results:
        return xml_results
    return parse_swift_test_text(output)


def normalize_test_id(test_id: str, framework: str) -> str:
    """Normalize test IDs by removing unstable runtime prefixes and standardizing formats.

    Args:
        test_id: Original test ID from parser
        framework: Test framework name (for framework-specific normalization rules)

    Returns:
        Normalized test ID with unstable prefixes removed and format standardized
    """
    # Universal pattern: Remove (N/M) or [N/M] prefixes (test execution order)
    normalized = re.sub(r"^[\(\[]?\s*\d+/\d+[\)\]]?\s+", "", test_id)

    # Universal pattern: Remove #N prefix (test numbering)
    normalized = re.sub(r"^#\s*\d+\s+", "", normalized)

    # Universal pattern: Remove "N. " prefix (numbered list)
    normalized = re.sub(r"^\d+\.\s+", "", normalized)

    # GTest/CTest normalization: standardize . vs :: separator
    # GTest uses formats like:
    #   - TestClass::TestName (standard with :: separator)
    #   - TestClass.TestName (sometimes uses . separator)
    #   - InstantiationName/TestClass.TestName/ParamIndex (parameterized tests)
    # We standardize to :: separator between class and test name
    if framework in ("gtest", "ctest"):
        # Handle parameterized test format: InstantiationName/TestClass.TestName/ParamIndex
        param_match = re.match(r"^([^/]+)/([^.]+)\.([^/]+)(?:/(.+))?$", normalized)
        if param_match:
            instantiation, classname, testname, param = param_match.groups()
            if param:
                normalized = f"{instantiation}/{classname}::{testname}/{param}"
            else:
                normalized = f"{instantiation}/{classname}::{testname}"
        # Handle simple format: TestClass.TestName -> TestClass::TestName
        elif "::" not in normalized and "." in normalized:
            # Only convert if it looks like ClassName.TestName (both parts are identifiers)
            parts = normalized.split(".", 1)
            if len(parts) == 2 and parts[0] and parts[1]:
                # Check both parts look like identifiers (start with letter/underscore)
                if re.match(r"^[A-Za-z_]", parts[0]) and re.match(r"^[A-Za-z_]", parts[1]):
                    normalized = f"{parts[0]}::{parts[1]}"

    # Pytest-specific normalization: convert path format to module format
    # e.g., "repo/tests/unit/test_foo.py::TestClass::test_method"
    #    -> "tests.unit.test_foo.TestClass::test_method"
    if framework in ("pytest", "python"):
        if "::" in normalized:
            parts = normalized.split("::")
            file_part = parts[0]
            # Remove common prefixes like "repo/", "src/", etc.
            file_part = re.sub(r"^(?:repo|src|source|lib|app)/", "", file_part)
            # Remove .py extension
            file_part = re.sub(r"\.py$", "", file_part)
            # Convert slashes to dots (path to module)
            file_part = file_part.replace("/", ".")
            
            # Reconstruct: module.class::method (standard pytest nodeid format)
            # If we have module::class::method, convert to module.class::method
            if len(parts) == 3:
                # file_part::class::method -> file_part.class::method
                normalized = f"{file_part}.{parts[1]}::{parts[2]}"
            elif len(parts) == 2:
                # file_part::method -> file_part::method (keep as is)
                normalized = f"{file_part}::{parts[1]}"
            else:
                # More parts, just join with ::
                normalized = "::".join([file_part] + parts[1:])
        else:
            # Handle case where it's just a file path without ::
            normalized = re.sub(r"^(?:repo|src|source|lib|app)/", "", normalized)
            normalized = re.sub(r"\.py$", "", normalized)
            normalized = normalized.replace("/", ".")

    return normalized


def parse_jest_vitest_console(output: str) -> dict[str, str] | None:
    """Parse Jest/Vitest console output (when JSON output is not available).

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
    """
    ansi_pattern = re.compile(r"\x1b\[[0-9;]*m")
    output = ansi_pattern.sub("", output)

    results = {}

    suite_pattern = re.compile(
        r"^(PASS|FAIL)\s+(?:\w+\s+)?(\S+\.(?:test|spec)\.[jt]sx?)(?:\s+\([^)]+\))?",
        re.MULTILINE,
    )

    for match in suite_pattern.finditer(output):
        status = match.group(1)
        test_file = match.group(2)
        results[test_file] = "PASSED" if status == "PASS" else "FAILED"

    vitest_file_pattern = re.compile(
        r"^\s*([✓✔]|[✕✗×])\s+(\S+\.(?:test|spec)\.[jt]sx?)\s+\([^)]+\)",
        re.MULTILINE,
    )

    for match in vitest_file_pattern.finditer(output):
        mark = match.group(1)
        test_file = match.group(2)
        if mark in "✓✔":
            results[test_file] = "PASSED"
        else:
            results[test_file] = "FAILED"

    check_pattern = re.compile(
        r"^\s*([✓✔]|[✕✗×])\s+(.+?)(?:\s+\(\d+\s*m?s\))?\s*$",
        re.MULTILINE,
    )

    for match in check_pattern.finditer(output):
        mark = match.group(1)
        test_name = match.group(2).strip()
        if (
            test_name.endswith((".ts", ".tsx", ".js", ".jsx"))
            and test_name in results
        ):
            continue
        if mark in "✓✔":
            results[test_name] = "PASSED"
        else:
            results[test_name] = "FAILED"

    return results if results else None


def parse_pytest_console(output: str) -> dict[str, str] | None:
    """Parse pytest console output (verbose mode with PASSED/FAILED markers).

    Handles two formats:
    1. Verbose mode: "test_file.py::TestClass::test_name PASSED"
    2. Short test summary: "FAILED test_file.py::TestClass::test_name"

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
    """
    results = {}

    # Pattern 1: Verbose mode - "test_id STATUS"
    verbose_pattern = re.compile(
        r'^([\w/\-\.]+(?:::[\w\-\[\]\(\),\s<>=\'\\"]+)+)\s+'
        r"(PASSED|FAILED|SKIPPED|ERROR|XFAIL|XPASS)",
        re.MULTILINE,
    )

    for match in verbose_pattern.finditer(output):
        test_id = match.group(1).strip()
        status = match.group(2)

        if status in ("PASSED", "XPASS"):
            results[test_id] = "PASSED"
        elif status in ("FAILED", "ERROR", "XFAIL"):
            results[test_id] = "FAILED"
        elif status == "SKIPPED":
            results[test_id] = "SKIPPED"

    # Pattern 2: Short test summary - "STATUS test_id" (used with parallel pytest / -n flag)
    # This section appears after "=== short test summary info ===" in pytest output
    # Matches: "FAILED path/to/test.py::TestClass::test_method" or with parameterized tests
    summary_pattern = re.compile(
        r"^(PASSED|FAILED|SKIPPED|ERROR|XFAIL|XPASS)\s+"
        r"(\S+\.py::\S+)",
        re.MULTILINE,
    )

    for match in summary_pattern.finditer(output):
        status = match.group(1)
        test_id = match.group(2).strip()

        # Don't overwrite if we already have a result from verbose output
        if test_id in results:
            continue

        if status in ("PASSED", "XPASS"):
            results[test_id] = "PASSED"
        elif status in ("FAILED", "ERROR", "XFAIL"):
            results[test_id] = "FAILED"
        elif status == "SKIPPED":
            results[test_id] = "SKIPPED"

    return results if results else None


def parse_make_text(output: str) -> dict[str, str] | None:
    """Parse make/cmake custom C test output.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If make tests failed to run (not the same as tests failing)
    """
    results = {}

    clean = re.sub(r"\x1b\[[0-9;]*m", "", output)

    current_test = None
    test_passed = True

    for line in clean.split("\n"):
        test_match = re.match(r"^(test_*\w+):\s*$", line.strip())
        if test_match:
            if current_test:
                results[current_test] = "PASSED" if test_passed else "FAILED"
            current_test = test_match.group(1)
            test_passed = True
            continue

        if "[PASS:" in line or "[PASS]" in line:
            pass
        elif "[FAIL:" in line or "[FAIL]" in line:
            test_passed = False

    if current_test:
        results[current_test] = "PASSED" if test_passed else "FAILED"

    if results:
        return results

    simple_pattern = re.compile(
        r"^(\w+):\s*(PASS|FAIL|OK|FAILED|ERROR)\s*$", re.IGNORECASE | re.MULTILINE
    )
    for match in simple_pattern.finditer(clean):
        test_name = match.group(1)
        status = match.group(2).upper()
        if status in ["PASS", "OK"]:
            results[test_name] = "PASSED"
        else:
            results[test_name] = "FAILED"

    if results:
        return results

    pass_desc_pattern = re.compile(
        r"^\[?(PASS|FAIL)\]?:?\s+(.+?)\s*$", re.IGNORECASE | re.MULTILINE
    )
    for match in pass_desc_pattern.finditer(clean):
        status = match.group(1).upper()
        test_name = match.group(2).strip()
        test_name = re.sub(r"^All\s+", "", test_name)
        if status == "PASS":
            results[test_name] = "PASSED"
        else:
            results[test_name] = "FAILED"

    if results:
        return results

    ctest_fail = re.compile(r"\[\s*FAILED\s*\]\s+(\S+)", re.IGNORECASE)

    for match in ctest_fail.finditer(clean):
        test_name = match.group(1)
        if not test_name.isdigit():
            results[test_name] = "FAILED"

    ctest_individual = re.compile(
        r"(?:\d+/\d+\s+)?Test\s+#?\d+:\s+(\S+)\s+\.+\s*(Passed|Failed|\*\*\*Failed)",
        re.IGNORECASE,
    )
    for match in ctest_individual.finditer(clean):
        test_name = match.group(1)
        status = match.group(2).lower()
        results[test_name] = "PASSED" if "pass" in status else "FAILED"

    return results if results else None


def parse_unity_text(output: str) -> dict[str, str] | None:
    """Parse Unity C test framework output.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If no Unity test output found
    """
    results = {}

    clean = re.sub(r"\x1b\[[0-9;]*m", "", output)

    unity_pattern = re.compile(
        r"^[^\s:]+:\d+:(\w+):(PASS|FAIL|IGNORE)\s*$", re.MULTILINE
    )

    for match in unity_pattern.finditer(clean):
        test_name = match.group(1)
        status = match.group(2).upper()
        if status == "PASS":
            results[test_name] = "PASSED"
        elif status == "FAIL":
            results[test_name] = "FAILED"
        else:
            results[test_name] = "SKIPPED"

    if results:
        return results

    simple_pattern = re.compile(r"^(\w+):(PASS|FAIL|IGNORE)\s*$", re.MULTILINE)
    for match in simple_pattern.finditer(clean):
        test_name = match.group(1)
        status = match.group(2).upper()
        if status == "PASS":
            results[test_name] = "PASSED"
        elif status == "FAIL":
            results[test_name] = "FAILED"
        else:
            results[test_name] = "SKIPPED"

    return results if results else None


def parse_tap_output(output: str) -> dict[str, str] | None:
    """Parse TAP (Test Anything Protocol) output.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If no TAP output found
    """
    results = {}

    clean = re.sub(r"\x1b\[[0-9;]*m", "", output)

    has_tap_version = "TAP version" in clean
    has_ok_not_ok = re.search(r"^(?:ok|not ok)\s+\d+", clean, re.MULTILINE)
    has_test_plan = re.search(r"^\d+\.\.\d+$", clean, re.MULTILINE)
    has_tap_summary = re.search(r"^#\s*(?:tests|pass|fail)\s+\d+", clean, re.MULTILINE)

    if not (has_tap_version or has_ok_not_ok or has_test_plan or has_tap_summary):
        return None

    tap_pattern = re.compile(
        r"^(ok|not ok)\s+(\d+)\s*(?:-\s*)?(.+?)?\s*(?:#\s*(SKIP|TODO).*)?$",
        re.MULTILINE | re.IGNORECASE,
    )

    for match in tap_pattern.finditer(clean):
        status = match.group(1).lower()
        test_num = match.group(2)
        test_name = match.group(3).strip() if match.group(3) else f"test_{test_num}"
        directive = match.group(4).upper() if match.group(4) else None

        test_name = re.sub(r"\s*#\s*time=[\d.]+\s*m?s?\s*$", "", test_name).strip()

        if not test_name:
            test_name = f"test_{test_num}"

        if directive == "SKIP":
            results[test_name] = "SKIPPED"
        elif directive == "TODO":
            results[test_name] = "PASSED" if status == "ok" else "SKIPPED"
        else:
            results[test_name] = "PASSED" if status == "ok" else "FAILED"

    return results if results else None


def parse_mocha_console(output: str) -> dict[str, str] | None:
    """Parse Mocha console output with checkmarks.

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If no Mocha console output found
    """
    results = {}

    clean = re.sub(r"\x1b\[[0-9;]*m", "", output)

    for line in clean.split("\n"):
        stripped = line.strip()
        if not stripped:
            continue

        pass_match = re.match(r"^\s*[✔✓]\s+(.+?)(?:\s+\(\d+\s*m?s\))?\s*$", line)
        if pass_match:
            test_name = pass_match.group(1).strip()
            results[test_name] = "PASSED"
            continue

        fail_match = re.match(r"^\s*\d+\)\s+(.+?)\s*$", line)
        if fail_match:
            test_name = fail_match.group(1).strip()
            results[test_name] = "FAILED"
            continue

        skip_match = re.match(r"^\s*-\s+(.+?)\s*$", line)
        if skip_match:
            test_name = skip_match.group(1).strip()
            results[test_name] = "SKIPPED"
            continue

    if results:
        return results

    passing = 0
    failing = 0
    pending = 0

    pass_match = re.search(r"(\d+)\s+passing(?:\s+\([^)]+\))?", clean)
    if pass_match:
        passing = int(pass_match.group(1))

    fail_match = re.search(r"(\d+)\s+failing", clean)
    if fail_match:
        failing = int(fail_match.group(1))

    pend_match = re.search(r"(\d+)\s+pending", clean)
    if pend_match:
        pending = int(pend_match.group(1))

    if passing > 0 or failing > 0:
        for i in range(passing):
            results[f"test_{i+1}"] = "PASSED"
        for i in range(failing):
            results[f"failing_test_{i+1}"] = "FAILED"
        for i in range(pending):
            results[f"pending_test_{i+1}"] = "SKIPPED"

    return results if results else None


def parse_swift_testing(output: str) -> dict[str, str] | None:
    """Parse Swift Testing framework output (Swift 6+).

    Returns:
        dict[str, str]: Test results mapping test IDs to status (PASSED/FAILED/SKIPPED)
        None: If no Swift Testing output found
    """
    results = {}

    clean = re.sub(r"\x1b\[[0-9;]*m", "", output)

    test_pattern = re.compile(
        r'^\s*([✔✓✘✗◇])\s+Test\s+"([^"]+)"\s+(passed|failed|skipped)',
        re.MULTILINE | re.IGNORECASE,
    )

    for match in test_pattern.finditer(clean):
        test_name = match.group(2)
        status = match.group(3).lower()

        if status == "passed":
            results[test_name] = "PASSED"
        elif status == "failed":
            results[test_name] = "FAILED"
        else:
            results[test_name] = "SKIPPED"

    if not results:
        summary_match = re.search(
            r"Test run with (\d+) tests? (passed|failed)", clean
        )
        if summary_match:
            results["test_run"] = (
                "PASSED" if summary_match.group(2) == "passed" else "FAILED"
            )

    return results if results else None


def parse_test_output(output: str, framework: str, validation_code: str | None = None) -> dict[str, str]:
    """
    Parse test output to extract individual test results.

    Args:
        output: Raw test output (stdout/stderr or file contents)
        framework: Test framework name (pytest, vitest, jest, go, junit, mocha, bespoke, etc.)
        validation_code: Optional validation code snippet for bespoke frameworks

    Returns: {'test_id': 'PASSED'|'FAILED'|'SKIPPED'}
    """
    # First, check if output is in the compact pre-processed format
    # This format is generated by the in-container parser (shared/parse_test_output.py)
    compact_results = parse_compact_format(output)
    if compact_results:
        return compact_results
    
    # Handle RAW_OUTPUT prefix from container parser
    # When the container parser couldn't parse, it prefixes with "RAW_OUTPUT\n"
    # Strip this prefix so we can try host-side parsing on the actual content
    if output.startswith("RAW_OUTPUT\n"):
        output = output[len("RAW_OUTPUT\n"):]
    
    # Extract result file content if present (added by run_with_patches)
    if "=== RESULT FILE:" in output:
        # Extract just the content after the header line
        lines = output.split("\n")
        content_lines = []
        in_result_file = False
        for line in lines:
            if line.startswith("=== RESULT FILE:"):
                in_result_file = True
                continue
            if in_result_file:
                content_lines.append(line)
        if content_lines:
            output = "\n".join(content_lines)
    
    # Handle bespoke frameworks specially (may need validation_code)
    if framework in ("bespoke", "bespoke_libgeos"):
        result = parse_bespoke_output(output, validation_code)
        return result or {}

    parsers = {
        "pytest": parse_junit_xml,
        "unittest": parse_junit_xml,
        "junit": parse_junit_xml,
        "maven": parse_maven_text_output,
        "gtest": parse_gtest_json,
        "cargo-nextest": parse_cargo_nextest,
        "go": parse_go_json,
        "jest": parse_jest_vitest_json,
        "vitest": parse_jest_vitest_json,
        "mocha": parse_mocha_json,
        "bun": parse_bun_text,
        "ctest": parse_junit_xml,
        "cppunit": parse_cppunit_text,
        "xctest": parse_xctest_output,
        "testing": parse_swift_testing,
        "busted": parse_junit_xml,
        "luaunit": parse_junit_xml,
        "telescope": parse_telescope_text,
        "lust": parse_lust_text,
        "minitest": parse_minitest_text,
        "make": parse_make_text,
        "cmake": parse_make_text,
        "unity": parse_unity_text,
        "tape": parse_tap_output,
        "tap": parse_tap_output,
        "hardhat": parse_mocha_json,
    }

    parser = parsers.get(framework)
    if parser:
        result = parser(output)
        if not result and framework in ["junit", "maven"]:
            result = parse_maven_text_output(output)
        if not result and framework in ["pytest", "unittest"]:
            result = parse_pytest_console(output)
        if not result and framework in ["jest", "vitest"]:
            result = parse_jest_vitest_console(output)
        if not result and framework in ["jest", "vitest"]:
            result = parse_tap_output(output)
        if not result and framework == "vitest":
            result = parse_mocha_json(output)
        if not result and framework in ["mocha", "hardhat"]:
            result = parse_mocha_console(output)
        if not result and framework in ["jest", "vitest", "mocha", "hardhat"]:
            result = parse_mocha_console(output)
        if not result and framework in ["ctest", "gtest"]:
            result = parse_gtest_console(output)
        if not result and framework in ["ctest", "gtest"]:
            result = parse_make_text(output)
        if not result and framework == "xctest":
            result = parse_swift_testing(output)
        if not result and framework == "xctest":
            result = parse_mocha_console(output)
        if not result and framework in ["tape", "tap"]:
            result = parse_tap_output(output)
        return result or {}

    # Unknown framework - warn and try universal fallbacks
    logger.warning(
        f"Unknown test framework '{framework}', using generic fallback parsers. "
        "Consider adding explicit support for better accuracy."
    )
    result = parse_tap_output(output)
    if result:
        return result

    result = parse_unity_text(output)
    if result:
        return result

    result = parse_swift_testing(output)
    if result:
        return result

    result = parse_mocha_console(output)
    if result:
        return result

    result = parse_make_text(output)
    if result:
        return result

    return {}
